version: "3.9"

services:

  backend:
    image: devops-gitops-backend:v1
    container_name: backend-container

    ports:
      - "8080:8080"

  frontend:
    image: devops-gitops-frontend:v1
    container_name: frontend-container

    ports:
      - "3000:80"

    depends_on:
      - backend